# Generated by Django 4.2.5 on 2023-10-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRigister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=20)),
                ("height", models.PositiveIntegerField(default=170)),
                ("weight", models.PositiveIntegerField(default=70)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="Male",
                        max_length=20,
                    ),
                ),
                ("intro", models.CharField(default="", max_length=20)),
            ],
        ),
    ]
