# Generated by Django 4.2.5 on 2023-11-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrigister",
            name="height",
        ),
        migrations.RemoveField(
            model_name="userrigister",
            name="intro",
        ),
        migrations.RemoveField(
            model_name="userrigister",
            name="weight",
        ),
        migrations.AddField(
            model_name="userrigister",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
    ]
