# Generated by Django 4.2.6 on 2023-10-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tourists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('University', models.CharField(max_length=50)),
                ('Program', models.CharField(max_length=50)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.IntegerField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Age', models.IntegerField(max_length=5)),
                ('Address', models.CharField(max_length=100)),
                ('Next_of_Kin', models.CharField(max_length=50)),
            ],
        ),
    ]
