# Generated by Django 4.2.6 on 2023-10-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourists',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tourists',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
