# Generated by Django 4.2.6 on 2023-10-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0002_alter_tourists_age_alter_tourists_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tourists',
            new_name='Tourist',
        ),
    ]
